server:
  port: 8080

spring:
  application:
    name: unify-backend
  devtools:
    restart:
      enabled: false

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: NON_NULL

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DB_NAME:default}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:default}
      lettuce:
        pool:
          max-active: 30
          max-idle: 15
          min-idle: 8
          max-wait: 15000

  cache:
    type: redis
    redis:
      time-to-live: 2400000

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:default}
  password: ${MAIL_PASSWORD:default}
  protocol: smtp
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    redis:
      enabled: true
    db:
      enabled: true
    websocket:
      enabled: true

  websocket:
    max-text-message-size: 65536
    max-binary-message-size: 65536
    max-sessions: 1000
    max-sessions-per-user: 5

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: WARN
        web:
          socket: WARN
        messaging: WARN
    com:
      unify:
        app:
          ws: ERROR
          messages: ERROR
          notifications: ERROR
          posts: ERROR
          comments: ERROR
  file:
    max-size: 200MB
    max-history: 10

springdoc:
  swagger-ui:
    use-root-path: true
    persist-authorization: true

var:
  avatar: https://res.cloudinary.com/daue063lh/image/upload/v1751362512/uploads/ao8cnnbqpztoc1oxnqew.jpg

jwt:
  signer-key: ${JWT_KEY:default}
  expiration-time-in-days: 7

unify:
  livekit-host: ${LIVEKIT_HOST:http://localhost:7880}
  livekit-api-key: ${LIVEKIT_API_KEY:default}
  livekit-api-secret: ${LIVEKIT_API_SECRET:default}
  livekit-ws-url: ${LIVEKIT_URL:ws://localhost:7880}
  app-uri: ${APP_URI:https://unifyapp.com}
  token-cleanup-job-cron: "0 2 * * *"
