server:
  port: 8080

spring:
  application:
    name: unify-backend

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DB_NAME:default}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:default}

  cache:
    type: redis

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:default}
  password: ${MAIL_PASSWORD:default}
  protocol: smtp
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

springdoc:
  swagger-ui:
    use-root-path: true
    persist-authorization: true

var:
  avatar: https://res.cloudinary.com/daue063lh/image/upload/v1751362512/uploads/ao8cnnbqpztoc1oxnqew.jpg

jwt:
  signerKey: ${JWT_KEY:default}

unify:
  livekit-host: ${LIVEKIT_HOST:http://localhost:7880}
  livekit-api-key: ${LIVEKIT_API_KEY:default}
  livekit-api-secret: ${LIVEKIT_API_SECRET:default}
  livekit-ws-url: ${LIVEKIT_URL:ws://localhost:7880}
  app-uri: ${APP_URI:https://unifyapp.com}
  trigger: true
