server:
  port: 8080
  # ✅ OPTIMIZED: Add server limits to prevent memory overflow
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    max-connections: 10000
    accept-count: 100
    connection-timeout: 20000

spring:
  application:
    name: unify-backend

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    default-property-inclusion: non_null

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    # ✅ OPTIMIZED: Add connection pool limits
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    # ✅ OPTIMIZED: Add JPA performance settings
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DB_NAME:default}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:default}
      # ✅ OPTIMIZED: Add Redis connection limits
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 10000

  cache:
    type: redis
    # ✅ OPTIMIZED: Add cache TTL settings
    redis:
      time-to-live: 1800000 # 30 minutes

mail:
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:default}
  password: ${MAIL_PASSWORD:default}
  protocol: smtp
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  # ✅ OPTIMIZED: Add health check settings
  health:
    redis:
      enabled: true
    db:
      enabled: true
    websocket:
      enabled: true

  websocket:
    max-text-message-size: 32768 # ✅ OPTIMIZED: 32KB - Reduced for better performance
    max-binary-message-size: 32768 # ✅ OPTIMIZED: 32KB - Reduced for better performance
    max-sessions: 500 # ✅ OPTIMIZED: Reduced to prevent memory overflow
    max-sessions-per-user: 3 # ✅ OPTIMIZED: Reduced to prevent abuse

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: WARN
        web:
          socket: WARN
        messaging: WARN
    com:
      unify:
        app:
          ws: ERROR
          messages: ERROR
          notifications: ERROR
          posts: ERROR
          comments: ERROR
  # ✅ OPTIMIZED: Add log file limits
  file:
    max-size: 100MB
    max-history: 7

springdoc:
  swagger-ui:
    use-root-path: true
    persist-authorization: true

var:
  avatar: https://res.cloudinary.com/daue063lh/image/upload/v1751362512/uploads/ao8cnnbqpztoc1oxnqew.jpg

jwt:
  signer-key: ${JWT_KEY:default}
  expiration-time-in-days: 7

unify:
  livekit-host: ${LIVEKIT_HOST:http://localhost:7880}
  livekit-api-key: ${LIVEKIT_API_KEY:default}
  livekit-api-secret: ${LIVEKIT_API_SECRET:default}
  livekit-ws-url: ${LIVEKIT_URL:ws://localhost:7880}
  app-uri: ${APP_URI:https://unifyapp.com}
  token-cleanup-job-cron: "0 2 * * *"
